### ISSUE TITLE
Why did you deprecate the Robust Autoencoder?

### ISSUE THREAD

**Issue by franz101** [dlegor/RAD_Version_Python#3]

**Comment by dlegor** [comment]
Hi @franz101,

The reason why the "deprecated" for autoencoder is, that I want to change the tfv1.*  to tfv2. *, and improve the numerical performance of the algorithms. This month I will start working on it.

**Comment by franz101** [comment]
Ah nice, I'll check back later. Why not use pytorch instead of tf?
